version: '3.8'

services:
  server-side:
    image: nestjs-app-runner-sample
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
